# Generated by Django 5.2.2 on 2025-06-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='subtitle',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comic',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
