# Generated by Django 5.2.2 on 2025-06-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_alter_comic_subtitle_alter_comic_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
