# Generated by Django 5.2.2 on 2025-06-19 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_comic_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='comics/pages/')),
                ('page_number', models.PositiveIntegerField()),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='Book.comic')),
            ],
            options={
                'ordering': ['page_number'],
            },
        ),
    ]
